apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-create-infra
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-create-infrastructure-nodes
      spec:
        object-templates-raw: |
          {{- $infrastructure_id := (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}
          {{- $worker_ms := (index (lookup "machine.openshift.io/v1beta1" "MachineSet" "openshift-machine-api" "").items 0) }}
          - complianceType: musthave
            objectDefinition:
              apiVersion: machine.openshift.io/v1beta1
              kind: MachineSet
              metadata:
                annotations:
                  machine.openshift.io/memoryMb: "32768"
                  machine.openshift.io/vCPU: "8"
                labels:
                  machine.openshift.io/cluster-api-cluster: '{{ $infrastructure_id }}'
                name: '{{ $infrastructure_id }}-infra'
                namespace: openshift-machine-api
              spec:
                replicas: 3
                selector:
                  matchLabels:
                    machine.openshift.io/cluster-api-cluster: '{{ $infrastructure_id }}'
                    machine.openshift.io/cluster-api-machineset: '{{ $infrastructure_id }}-infra'
                template:
                  metadata:
                    labels:
                      machine.openshift.io/cluster-api-cluster: '{{ $infrastructure_id }}'
                      machine.openshift.io/cluster-api-machine-role: infra
                      machine.openshift.io/cluster-api-machine-type: infra
                      machine.openshift.io/cluster-api-machineset: '{{ $infrastructure_id}}-infra'
                  spec:
                    lifecycleHooks: {}
                    metadata: 
                      labels:
                        node-role.kubernetes.io/infra: ""
                    taints:
                      - key: infra
                        value: reserved
                        effect: NoSchedule
                      - key: infra
                        value: reserved
                        effect: NoExecute
                    providerSpec:
                      value:
                        apiVersion: machine.openshift.io/v1beta1
                        credentialsSecret:
                          name: vsphere-cloud-credentials
                        diskGiB: 120
                        kind: VSphereMachineProviderSpec
                        memoryMiB: 32768
                        metadata:
                          creationTimestamp: null
                        network:
                          devices:
                          - networkName: {{ (index ($worker_ms.spec.template.spec.providerSpec.value.network).devices 0).networkName }}
                        numCPUs: 8
                        numCoresPerSocket: 4
                        snapshot: ""
                        template: {{ $infrastructure_id }}-rhcos
                        userDataSecret:
                          name: worker-user-data
                        workspace:
                          datacenter: '{{ $worker_ms.spec.template.spec.providerSpec.value.workspace.datacenter }}'
                          datastore:  '{{ $worker_ms.spec.template.spec.providerSpec.value.workspace.datastore }}'
                          {{- if $worker_ms.spec.template.spec.providerSpec.value.workspace.folder }}
                          folder: '{{ $worker_ms.spec.template.spec.providerSpec.value.workspace.folder }}'
                          {{- end }}
                          resourcePool: '{{ $worker_ms.spec.template.spec.providerSpec.value.workspace.resourcePool }}'
                          server: '{{ $worker_ms.spec.template.spec.providerSpec.value.workspace.server}}'
        severity: medium
  remediationAction: inform
