apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-oauth-configure
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-oauth-configuration
      spec:
        severity: medium
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec:
              tokenConfig:
                accessTokenMaxAgeSeconds: 604800
  remediationAction: inform
