apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pl-move-ingress-placement-binding
  namespace: acm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-infrastructure
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: pl-move-ingress
