apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pb-gitops-install
  namespace: acm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-infrastructure
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: openshift-gitops-installed
