apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  creationTimestamp: "2023-12-18T22:26:05Z"
  generation: 17
  name: pl-create-infra-2
  namespace: acm-policies
  resourceVersion: "1885725"
  uid: 1dbcccb1-86b2-4f7e-8ba4-26ef904ea75e
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-create-infrastructure-nodes-2
      spec:
        namespaceSelector:
          exclude: []
          include:
          - openshift-machine-api
        object-templates-raw: |
          {{- $infrastructure_id := (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}
          - complianceType: musthave
            objectDefinition:
              apiVersion: machine.openshift.io/v1beta1
              kind: MachineSet
              metadata:
                annotations:
                  machine.openshift.io/memoryMb: "32768"
                  machine.openshift.io/vCPU: "8"
                labels:
                  machine.openshift.io/cluster-api-cluster: '{{ $infrastructure_id }}'
                name: '{{ $infrastructure_id }}-infra'
                namespace: openshift-machine-api
              spec:
                replicas: 3
                selector:
                  matchLabels:
                    machine.openshift.io/cluster-api-cluster: '{{ $infrastructure_id }}'
                    machine.openshift.io/cluster-api-machineset: '{{ $infrastructure_id }}-infra'
                template:
                  metadata:
                    labels:
                      machine.openshift.io/cluster-api-cluster: '{{ $infrastructure_id }}'
                      machine.openshift.io/cluster-api-machine-role: infra
                      machine.openshift.io/cluster-api-machine-type: infra
                      machine.openshift.io/cluster-api-machineset: '{{ $infrastructure_id}}-infra'
                  spec:
                    lifecycleHooks: {}
                    metadata: 
                      labels:
                        node-role.kubernetes.io/infra: ""
                    providerSpec:
                      value:
                        apiVersion: machine.openshift.io/v1beta1
                        credentialsSecret:
                          name: vsphere-cloud-credentials
                        diskGiB: 120
                        kind: VSphereMachineProviderSpec
                        memoryMiB: 32768
                        metadata:
                          creationTimestamp: null
                        network:
                          devices:
                          - networkName: <FILL_IN>
                        numCPUs: 8
                        numCoresPerSocket: 4
                        snapshot: ""
                        template: {{ $infrastructure_id }}-rhcos
                        userDataSecret:
                          name: worker-user-data
                        workspace:
                          datacenter: <FILL_IN>
                          datastore: <FILL_IN>
                          folder: <FILL_IN>
                          resourcePool: <FILL_IN>
                          server: <FILL_IN>
        severity: medium
  remediationAction: inform
